# Generated by Django 4.0.4 on 2022-04-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=150)),
                ('img', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tabla_gatos',
            },
        ),
    ]
