# Generated by Django 4.0.4 on 2022-04-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
