# Generated by Django 4.0.4 on 2022-04-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatos',
            name='img',
        ),
    ]
