# Generated by Django 4.0.4 on 2022-04-26 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_gatos_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('rut', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('fecha_nac', models.DateTimeField()),
                ('telefono', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=150)),
                ('tipo_vivienda', models.CharField(max_length=50)),
                ('gatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gatos')),
            ],
            options={
                'db_table': 'tabla_postulaciones',
            },
        ),
    ]
