# Generated by Django 4.0.4 on 2022-04-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_postulacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulacion',
            old_name='ciudad',
            new_name='comunas',
        ),
        migrations.RenameField(
            model_name='postulacion',
            old_name='region',
            new_name='regiones',
        ),
    ]
